using System.Collections.ObjectModel;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var cities = Cities.FromJson(jsonString);

namespace DopeWars.Models;

public partial class Cities
{
    [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
    public string Name { get; set; }
}

public partial class Cities
{
    public static ObservableCollection<Cities> FromJson(string json) => JsonConvert.DeserializeObject<ObservableCollection<Cities>>(json, CitiesConverter.CitiesSettings);
}

public static class Serialize
{
    public static string ToJson(this ObservableCollection<Cities> self) => JsonConvert.SerializeObject(self, CitiesConverter.CitiesSettings);
}

internal static class CitiesConverter
{
    public static readonly JsonSerializerSettings CitiesSettings = new JsonSerializerSettings
    {
        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
        DateParseHandling = DateParseHandling.None,
        Converters =
        {
            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
        },
    };
}
